[[preface]]
== Preface

Who This Book is For

If you are trying to figure out how senior devs seem to magically know how everything works and how they understand complex concepts so quickly, I'm going to show you how. At this point in your career, you've probably been working as a software developer for a few years. You know how to complete your tasks with solid code regardless of whether it's on the front-end or back-end.

While you might have some knowledge across the full-stack, it's likely you have a focus on one side over the other. On the front-end, you should be familiar with things like making responsive layouts, fetching data from APIs, and some of the frameworks like React, Astro, or Vue. On the back-end, you've done some database migrations, built some APIs, and handled some basic authentication flows.

You likely also have skills like using Git with any of the repo hosting services, like GitHub or GitLab, and using different tools to test your changes. You may have worked on one project for years or you might have hopped around, but the scope of your work has typically fallen into some of the concepts mentioned.

Now you're ready to move to the next level in your career. That means learning how the whole system works and why technical decisions are made. That's what will be covered in this book.

What You Will Learn

The high level of what you're going to learn in this book is everything it takes to create a full-stack web application hosted on a cloud platform. You're going to learn how to find where the business logic for every app comes from. You're going to understand how to decide between different architectures, third-party services, and tools to create a maintainable application.

You are going to learn the subtle, yet deep skills it takes to become a senior developer. This book is going to give you strategies for working with different teams and understanding how product decisions are made. You'll also deepen your existing skills to cover the full-stack confidently.

Regardless of whether you start on the front-end or back-end, you're going to learn about design and development principles and when to apply them. You'll learn all of these things as you go through the software development lifecycle (SDLC) of a project in this book and build a production-like application.

Think of this book as a reference you can pick up at any point in the SDLC and use it as a checklist. You will learn all of the essential parts that need to be considered for app development so that you know exactly what to do when a question comes up. By the time you finish, you'll know how, why, and when to make techincal decisions and how the business requirements evolve.

What This Book is Not

This book is not a deep dive into any specific set of tools and it will not teach you general JavaScript programming. There will be a large range of topics covered in this book with accompanying examples to demonstrate senior-level considerations, but it is expected that you know how to read code, debug issues, and find additional learning resources.

Since there are so many topics covered, there will be strategies discussed along with the code. These strategies are meant to be tools you can bring to any project you work on, although they might not work on every project. There isn't a single approach that would work for any two projects because everything has its own nuances. So the goal is to give you a number of options you can choose from as needed.

There will be some parts of the book that need a much deeper explanation than a chapter or section can provide and there will be links to other resources. No book can adquately cover all of the topics presented here and I want to make sure you get all of the information you need. So while some topics will be light on the full implementation details, there will always be links to complementary resources.