[[preface]]
== Preface

If you are trying to figure out how senior devs seem to magically know how everything works and how they understand complex concepts so quickly, I'm going to show you how. Over the past 10 years, I've crammed in a lot of experience with different companies ranging from early stage startups to enterprise companies with thousands of global employees. At the beginning of my career, I dived into tech really deeply. I would work 80 hour weeks and still find time to read, present at conferences, and do personal projects.

I will never recommend that approach to anyone because of all the negative side effects. But it's how I was able to take in all of the knowledge I'm going to share with you throughout this book. By working on a wide range of projects, I've seen a number of architectures, tools, and the pros and cons to help make maintainable decisions.

There's so much it takes to write good software that doesn't involve programming at all. Many of the things senior software engineers know come from a lot of domain knowledge and understanding the business logic before writing anything. They'll take the time to create diagrams, documentation, and really dig into tools to see what fits the problem the best. The trick is that none of this information is given in a straightforward way.

All of the info they get comes from a lot of conversations and moving through the technical parts of the project and they slowly compile it. That's where the magic comes from. That's what I hope to show you how to do in this book.

Who This Book is For
What You Will Learn
What This Book is Not (optional)